// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTree: typeof import('element-plus/es')['ElTree']
    IconifyIcon: typeof import('./src/components/my-icon/iconify-icon.vue')['default']
    LayoutBreadcrumb: typeof import('./src/components/my-layout/layout-breadcrumb.vue')['default']
    LayoutHeader: typeof import('./src/components/my-layout/layout-header.vue')['default']
    LayoutLogo: typeof import('./src/components/my-layout/layout-logo.vue')['default']
    LayoutSideMenu: typeof import('./src/components/my-layout/layout-side-menu.vue')['default']
    LayoutSideMenuItem: typeof import('./src/components/my-layout/layout-side-menu-item.vue')['default']
    MainContainer: typeof import('./src/components/main-container/index.vue')['default']
    MyIcon: typeof import('./src/components/my-icon/index.vue')['default']
    MyLayout: typeof import('./src/components/my-layout/index.vue')['default']
    MyRouterLink: typeof import('./src/components/my-router-link/index.vue')['default']
    ToggleMenuBar: typeof import('./src/components/my-layout/toggle-menu-bar.vue')['default']
  }
}

export { }
