/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HelloWorld: typeof import('./components/hello-world.vue')['default']
    Icon: typeof import('./components/my-image-uploader/icon.vue')['default']
    LayoutBreadcrumb: typeof import('./components/my-layout/layout-breadcrumb.vue')['default']
    LayoutHeader: typeof import('./components/my-layout/layout-header.vue')['default']
    LayoutLogo: typeof import('./components/my-layout/layout-logo.vue')['default']
    LayoutMenu: typeof import('./components/my-layout/layout-menu.vue')['default']
    LayoutMenuItem: typeof import('./components/my-layout/layout-menu-item.vue')['default']
    MainContainer: typeof import('./components/main-container/index.vue')['default']
    MyFormContainer: typeof import('./components/my-form-container/index.vue')['default']
    MyIcon: typeof import('./components/my-icon/index.vue')['default']
    MyImageUploader: typeof import('./components/my-image-uploader/index.vue')['default']
    MyLayout: typeof import('./components/my-layout/index.vue')['default']
    MyPagination: typeof import('./components/my-pagination/index.vue')['default']
    MyRouterLink: typeof import('./components/my-router-link/index.vue')['default']
    MyRouterView: typeof import('./components/my-router-view.vue')['default']
    MyTinymceEditor: typeof import('./components/my-tinymce-editor/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TinymceEditor: typeof import('./components/tinymce-editor/index.vue')['default']
    ToggleMenuBar: typeof import('./components/my-layout/toggle-menu-bar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
